-- Create cars table
CREATE TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate TEXT NOT NULL,
    brand TEXT,
    model TEXT,
    color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create parking_lots table
CREATE TABLE IF NOT EXISTS parking_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag TEXT NOT NULL,
    occupied BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create parkings table
CREATE TABLE IF NOT EXISTS parkings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
    lot_id BIGINT REFERENCES parking_lots(id) ON DELETE SET NULL,
    start_time TEXT,
    end_time TEXT,
    date TEXT,
    duration REAL,
    rate REAL,
    total REAL,
    payment_generated BOOLEAN DEFAULT FALSE,
    payment_paid BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed some initial parking spots
INSERT INTO parking_lots (tag)
SELECT 'Spot ' || i
FROM generate_series(1, 10) AS i;
